# Generated by Django 2.2.4 on 2021-06-04 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('book', '0018_auto_20210604_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField(verbose_name='EXPLAIN')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comments',
                'ordering': ('-create_dt',),
            },
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField(verbose_name='EXPLAIN')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sub',
                'verbose_name_plural': 'subs',
                'db_table': 'subs',
                'ordering': ('-create_dt',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='SLUG')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='SUBJECT')),
                ('explain', models.TextField(verbose_name='EXPLAIN')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.SubCategory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'posts',
                'ordering': ('-create_dt',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
