# Generated by Django 2.2.4 on 2021-06-04 02:59

from django.db import migrations
import login.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=login.fields.ThumbnailImageField(blank=True, null=True, upload_to='blog/%Y/%m'),
        ),
    ]
