# Generated by Django 2.2.4 on 2021-05-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NAME'),
        ),
        migrations.AddField(
            model_name='user',
            name='sosok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SOSOK'),
        ),
    ]
