# Generated by Django 2.2.4 on 2021-05-06 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='NAME')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='SLUG')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='SLUG')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.MainCategory')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='NAME')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='SLUG')),
                ('explain', models.TextField(verbose_name='EXPLAIN')),
                ('score', models.FloatField(default=0)),
                ('page', models.IntegerField(default=0)),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='AUTHOR')),
                ('publication', models.CharField(blank=True, max_length=100, verbose_name='PUBLICATION')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book/%Y/%m')),
                ('image_sub1', models.ImageField(blank=True, null=True, upload_to='book/%Y/%m')),
                ('image_sub2', models.ImageField(blank=True, null=True, upload_to='book/%Y/%m')),
                ('image_sub3', models.ImageField(blank=True, null=True, upload_to='book/%Y/%m')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.SubCategory')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('wish', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'db_table': 'books',
            },
        ),
    ]
