# Generated by Django 2.2.4 on 2021-05-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.FloatField(default=0),
        ),
    ]
