# Generated by Django 2.2.4 on 2021-05-17 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_book_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='SUBJECT')),
                ('explain', models.TextField(verbose_name='EXPLAIN')),
                ('score', models.FloatField(blank=True, default=0)),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'db_table': 'reviews',
                'ordering': ('-create_dt',),
            },
        ),
    ]
