# Generated by Django 2.2.4 on 2021-05-22 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210522_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='explain',
            field=models.TextField(blank=True, verbose_name='EXPLAIN'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
